apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log-ingestion.fullname" . }}-secrets
  labels:
    {{- include "log-ingestion.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-username: {{ .Values.secrets.rabbitmqUsername | b64enc | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | b64enc | quote }}
